language: c
sudo: false
compiler:
- clang
- gcc

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.5
        packages:
            - cmake
            - llvm-3.5
            - llvm-3.5-dev
script:
    - mkdir -p build install
    - cd build
    - cmake ../ -DCMAKE_INSTALL_PREFIX=../install
    - make
    - make test
    - make install
